### ISSUE TITLE
Invisible Cows

### ISSUE THREAD

**Issue by A5ho9999** [Faboslav/friends-and-foes-flowery-mooblooms#4]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.14.25

### Mod version information

friendsandfoes-flowerymooblooms-fabric-mc1.20.1-2.0.0.jar

### Expected Behavior

To see and interact with Cows

### Actual Behavior

Cows are invisible, they have no hit boxes and can't be interacted with by players. They still randomly leave flowers & make sounds. They can be modified with commands, however things like fire, glowing other effects weren't rendered.

### Reproduction Steps

1. Grab Spawn Egg
2. Place spawn Egg

### Screenshots & files

![1](https://i.imgur.com/KLiIAqq.png)

**Comment by Faboslav** [comment]
There is nothing on the screenshot, but also can you try to reproduce this with friends&foes alone please?

**Comment by A5ho9999** [comment]
The screenshot is showing that there is a Moobloom entity (a poppy one specifically) despite it not being visible (It should be within in the fences)

I went to try with just the Friends & Foes and everything was normal, put back in the flowery mooblooms and everything was still fine. So I doubled checked on a test server and they still appeared. Returned to the main server and once again still there. Now I'm generally confused as to what happened. As it everyone on the server (4+ people) couldn't see them earlier. I guess this can be closed

**Comment by Faboslav** [comment]
That is great to hear! In case of anything let me know please :).

**Comment by A5ho9999** [comment]
So still somewhat an issue, after restarting the game they once again don't show up but if you join a singleplayer world they do. So something isn't being generated when a player joins a server with the mod?

**Comment by Faboslav** [comment]
This is related to https://github.com/Faboslav/friends-and-foes/issues/169, will try to fix it as soon as possible.
