### ISSUE TITLE
getVariant() is null

### ISSUE THREAD

**Issue by iMahco** [Faboslav/friends-and-foes-flowery-mooblooms#5]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

Forge 47.2.0

### Mod version information

2.0.0

### Reproduction Steps

The problem seems to occur once you add the flowery mooblooms mod!
Using only friend&foes is okay.

1. Start a Forge dedicated server, in my instance it was using version 47.2.0 with minecraft 1.20.1
2. Add in friends & foes 2.0.5
3. Add in flowery mooblooms 2.0.0
4. Start the server and using the same setup client, connect to it.
5. Use a Moobloom egg anywhere.
6. crash

Absolutely do **Not** start a singleplayer world, doing so will skip the crash and can be used as a temporary fix!
Just connect to the server without ever going into singeplayer to experience said crash.

### Crash Report and latest.log

[latest.log](https://github.com/Faboslav/friends-and-foes-flowery-mooblooms/files/13708102/latest.log)

**Comment by iMahco** [comment]
[crash-2023-12-18_12.56.48-client.txt](https://github.com/Faboslav/friends-and-foes-flowery-mooblooms/files/13708162/crash-2023-12-18_12.56.48-client.txt)
forgot the crash report!

**Comment by Faboslav** [comment]
Thank you for your detailed report, i will try release a fix tomorrow. Not of this addon, but of the main mod, where the problem is.

**Comment by iMahco** [comment]
Problem solved with that version 2.0.6 release!
Thanks so much for such a FAST fix!! <3
