### ISSUE TITLE
[FEATURE] Fresh Animations for Mooblooms

### ISSUE THREAD

**Issue by makumaku1974** [Faboslav/friends-and-foes-flowery-mooblooms#8]
Mooblooms kinda bit stiff imo and need to take out the stiffness and replace it with jolliness within Mooblooms. I'm still the same guy who requested the Variant and Ventures x Fresh Animations Compatibility.

**Comment by digi2303** [comment]
You can use [Freshly Modded](https://modrinth.com/resourcepack/freshly-modded)

**Comment by Faboslav** [comment]
I think moobloom should work even without freshly modded with fresh animations.

**Comment by digi2303** [comment]
I tried and Moobloom didn't work.

**Comment by makumaku1974** [comment]
> I think moobloom should work even without freshly modded with fresh animations.

Custom models sometimes do not render with Fresh Animations. Only with Vanilla models like replacing its skin. There is a moobloom mod that does this basically replacing only it's skin without the flowers. But it looks off without the flowers which i prefer your mod than the other.

**Comment by Faboslav** [comment]
Yeah, but i am using the original model, so that should be working, will need to test this more.

**Comment by makumaku1974** [comment]
It's actually working lmao. my bad for making a report to this im closing it now. I got it fixed by using freshly modded.
